name: example
version: 0.0.1
description: A zero project
main: lib/main.dart
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  zero:
    git:
      url: https://github.com/bryanbill/zero 

dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.0
